import sanitizeHtml from "sanitize-html";
import { Column, Entity, PrimaryGeneratedColumn } from "typeorm";
import z from "zod";

/**
 * The Schema for creating or updating a Recipe.
 *
 * The ID is generated by the database and therefore not part of this schema.
 * The ownerUserId is determined by the authentication context and therefore
 * also not part of this schema.
 */
export const RecipeUpdateCreateSchema = z.object({
    title: z
        // Input Validation: Ensure the format matches our expectations.
        .string()
        .min(1)
        .max(512)
        // Input Sanitization: Remove any potentially dangerous HTML tags.
        // We transform incoming input directly by using the sanitize-html
        // library in Zod's transform method.
        .transform((s) => sanitizeHtml(s)),
    description: z
        // Input Validation: Ensure the format matches our expectations.
        .string()
        .min(1)
        .max(2048)
        // Input Sanitization: Remove any potentially dangerous HTML tags.
        // We transform incoming input directly by using the sanitize-html
        // library in Zod's transform method.
        .transform((s) => sanitizeHtml(s)),
    // By default, recipes are public - so we set an explicit default here.
    isPrivate: z.boolean().default(false),
    // We'll store the ingredients as JSON-encoded string for simplicity and
    // therfore won't validate the structure here.
    ingredients: z.string(),
    // We'll store the steps as JSON-encoded string for simplicity and
    // therefore won't validate the structure here.
    steps: z.string(),
});

@Entity()
export class Recipe {
    constructor(
        id: number,
        ownerUserId: string,
        title: string,
        description: string,
        isPrivate: boolean,
        ingredients: string,
        steps: string,
    ) {
        this.id = id;
        this.ownerUserId = ownerUserId;
        this.title = title;
        this.description = description;
        this.isPrivate = isPrivate;
        this.ingredients = ingredients;
        this.steps = steps;
    }

    @PrimaryGeneratedColumn({ type: "int" })
    id: number;

    @Column({ type: "text" })
    ownerUserId: string;

    @Column({ type: "text" })
    title: string;

    @Column({ type: "text" })
    description: string;

    @Column({ type: "boolean" })
    isPrivate: boolean;

    // We'll store the ingredients as JSON-encoded string for simplicity
    @Column({ type: "text" })
    ingredients: string;

    // We'll store the steps as JSON-encoded string for simplicity
    @Column({ type: "text" })
    steps: string;
}
